### ISSUE TITLE
Using `plot()` to make a line graph doesn't cope well if there's no data.

### ISSUE THREAD

**Issue by SolarDrew** [DKISTDC/dkist#473]
Scenario A:

```
import dkist
from dkist.data.sample import VISP_BKPLX
import matplotlib.pyplot as plt

ds.plot(plot_axes=[None, None, 'x', None])
plt.show()
```
This plots fine initially but then clicking to cycle through the Stokes axis gives:

```
Traceback (most recent call last):
  File "/home/drew/mambaforge/envs/dkist-workshop/lib/python3.13/site-packages/matplotlib/cbook.py", line 298, in process
    func(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "/home/drew/mambaforge/envs/dkist-workshop/lib/python3.13/site-packages/matplotlib/widgets.py", line 592, in <lambda>
    return self._observers.connect('changed', lambda val: func(val))
                                                          ~~~~^^^^^
  File "/home/drew/mambaforge/envs/dkist-workshop/lib/python3.13/site-packages/mpl_animators/base.py", line 376, in _slider_changed
    self.slider_functions[slider.slider_ind](val, self.im, slider)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drew/mambaforge/envs/dkist-workshop/lib/python3.13/site-packages/mpl_animators/wcs.py", line 231, in update_plot
    self.update_plot_1d(val, artist, slider)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/drew/mambaforge/envs/dkist-workshop/lib/python3.13/site-packages/mpl_animators/wcs.py", line 280, in update_plot_1d
    self.axes.set_ylim(float(self.data[self.frame_index].min()),
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                       float(self.data[self.frame_index].max()))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drew/mambaforge/envs/dkist-workshop/lib/python3.13/site-packages/matplotlib/axes/_base.py", line 3973, in set_ylim
    return self.yaxis._set_lim(bottom, top, emit=emit, auto=auto)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drew/mambaforge/envs/dkist-workshop/lib/python3.13/site-packages/matplotlib/axis.py", line 1236, in _set_lim
    v0 = self.axes._validate_converted_limits(v0, self.convert_units)
  File "/home/drew/mambaforge/envs/dkist-workshop/lib/python3.13/site-packages/matplotlib/axes/_base.py", line 3660, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf

```

Scenario B:

```
>>> %timeit ds[0, 0, :, 0].plot() # Sample Stokes I data is available
249 ms ± 9.52 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

>>> %timeit ds[1, 0, :, 0].plot() # This data isn't
1min 13s ± 838 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Scenario A also takes a while to do anything once it throws the error, so I suspect these things may be linked.

**Comment by SolarDrew** [comment]
A similar error occurs when updating a 2D plot if `clip_interval` is set, due to being unable to calculate `vmin` and `vmax` when data is missing.
